import { z } from "zod";

// Adaptive frame budget. 3 default. Up to FAILURE_FRAMES_MAX when the
// digest's failurePoint has many precedingActions (signal of a complex
// failure with buildup worth visualizing).
export const FAILURE_FRAMES_MIN = 3;
export const FAILURE_FRAMES_MAX = 7;
export const FAILURE_FRAMES_ADAPTIVE_THRESHOLD = 5;

// One rendered keyframe at a single timestamp. base64Png is raw base64
// (no `data:image/png;base64,` prefix). The agent service prepends that
// prefix when building multimodal messages.
export const failureFrameSchema = z.object({
  timestamp: z.iso.datetime(),
  offsetMs: z.number().int(),
  base64Png: z.string().min(1),
  captionHint: z.string(),
});
export type FailureFrame = z.infer<typeof failureFrameSchema>;

// Text caption produced by the captioner pipeline for text-only workspaces.
// Generated by a fixed shared vision model (default: gpt-4o-mini) describing
// what's visible in the frame. Never replaces frames for vision-capable
// workspaces.
export const failureFrameCaptionSchema = z.object({
  timestamp: z.iso.datetime(),
  offsetMs: z.number().int(),
  captionHint: z.string(),
  captionText: z.string().min(1),
});
export type FailureFrameCaption = z.infer<typeof failureFrameCaptionSchema>;
